### PR TITLE
[FX-271] Add wrapper methods to set file name and size

### PR DESCRIPTION
**Pull request by mLangDephy**
# Description

Allow python script to be able to set the file name and size of the logged files.

# Changes

Adds two new methods that set the _dataLogger and _debugLogger objects in fx_plan_stack 
[FX-235] required for this functionality

# Test Plan

Run python script to control motor as usual, however, call the method "setFileName" and "setFileSize" by passing in a string (char *) and an int.

# Expected Results

-If "file" is passed into setFileName, the resulting data log files should be file.1.csv, file.2.csv etc, and the resulting debug log files should be fileDEBUG.1.txt, fileDEBUG.2.txt etc.

# Requirements
Edit the list accordingly.
- [x] Tested on Windows.
- [x] Tested on Linux.
- [x] Tested on RPi.
- [x] Connected ActPack and runs scripts.

[FX-235]: https://dephyinc.atlassian.net/browse/FX-235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by jcoughlin11 — CHANGES_REQUESTED** [review]
The only comment I have is if you wouldn't mind making `setFileSize` and `setFileName` snake case, e.g., `set_file_name` and `set_file_size`. 

The failing checks are due to the linter. You can run the linter locally by installing [poetry](https://python-poetry.org/docs/#installation) and then, from the repo, running `poetry install --with dev` to install the development dependencies. The last thing is to then run the linter via `poetry run nox -s lint`

Other than those small things, it looks great! Awesome job!

**Comment by mLangDephy** [comment]
Will do. Thanks!

**Comment by mLangDephy** [comment]
FYI in flexsea/utilities/system.py I changed the "os" library to the "platform" because of this error..."flexsea\utilities\system.py:29:18: E1101: Module 'os' has no 'uname' member; maybe 'name'? (no-member)". The change there was "machine = os.uname().machine" --> "machine = (platform.machine())"

**Comment by mLangDephy** [comment]
Another FYI, FX-235 in fx_plan_stack is blocking this merge.

**Review by jcoughlin11 — APPROVED** [review]

**Comment by jcoughlin11** [comment]
Do you want me to hold off on merging this, then?

**Comment by mLangDephy** [comment]
Yes

**Pull request merged**
